<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>NewAgeWorship.WebWorker</AssemblyName>
    <RootNamespace>NewAgeWorship.WebWorker</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
